###
POST http://127.0.0.1:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
GET http://127.0.0.1:8080/api/account/info
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiVVNFUixBRE1JTiIsImlkIjoxLCJleHAiOjE2ODk2NTAwNDAsImlhdCI6MTY4OTYwNjg0MCwidXNlcm5hbWUiOiJhZG1pbiJ9.YYsgDMnsGIdUJ_5bsR-8VY_WjueYj5G5oBe_mZvkdcyNeFhI-OGvurPhevTJyrkOkCgmnxxnhAAvGCRdCUdWd6n0aKDHzMMoVlsfOOcKvftKzppZrNQ6mhtR4bTcTRmbXf1hk_645z57sSgdD9lJBuNLTVDcnJ9FYxJrW4bokmK1p1UNdQ3i7iIWGyJHMNTY7GOQCNbh4cd1eSLz26C76V7HAOV2l0Z_zpHx9ZGMDpjDnsW0qprPPyxYjOKAd_ThuF26iSYsfTDbIdBVHEiwsymd7xcXBLuaZpdc1DSJO2Rdepn8mB1g7NasEEPOkVnEI4FsRgqWSR41FVP0TwwCsw
